# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "⚠️ Breaking changes"
    label: "breaking-change"
  - title: "🚀 Features"
    label: "enhancement"
  - title: "📘 Documentation"
    label: "documentation"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "📈 Dependency updates"
    labels:
      - "dependency-update"
      - "scala-steward"
exclude-labels:
  - 'build'
template: |
  ## What's changed

  $CHANGES
autolabeler:
  - label: "enhancement"
    branch:
      - '/enhancement\/.+/'
      - '/feature\/.+/'
  - label: "documentation"
    files:
      - "*.md"
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
  - label: "breaking-change"
    branch:
      - '/breaking\/.+/'
      - '/break\/.+/'
  - label: "bug"
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
  - label: "tests"
    branch:
      - '/test\/.+/'
      - '/tests\/.+/'
  - label: "dependency-update"
    branch:
      - '/dep\/.+/'
      - '/dependency\/.+/'
      - '/dependency-update\/.+/'
  - label: "scala-steward"
    branch:
      - '/update\/.+/'
  - label: "build"
    branch:
      - '/build\/.*/'
    files:
      - "project/**"
