sbt-build {
  scala-versions = ["~2.12.21", "~2.13.18", "~3.3.7"]
}

documentation = [
  "org.http4s::http4s-blaze-client:0.23.17"
]

http4s-munit = [
  "io.circe::circe-parser:0.14.15"
  "org.http4s::http4s-client:0.23.33"
  "org.http4s::http4s-dsl:0.23.33"
  "org.scalameta::munit:1.0.4"
  "org.typelevel::munit-cats-effect:2.1.0"
  "ch.qos.logback:logback-classic:1.5.26:test"
  "com.dimafeng::testcontainers-scala-munit:0.41.8:test"
  "org.http4s::http4s-circe:0.23.33:test"
  "org.http4s::http4s-ember-client:0.23.33:test"
]
