sbt-build {
  dependencies = [
    "ch.epfl.scala:sbt-scalafix:0.14.6:sbt-plugin"
    "ch.epfl.scala:sbt-version-policy:3.2.1:sbt-plugin"
    "com.alejandrohdezma:sbt-ci:3.0.0:sbt-plugin"
    "com.alejandrohdezma:sbt-fix:0.8.0:sbt-plugin"
    "com.alejandrohdezma:sbt-github-header:0.13.0:sbt-plugin"
    "com.alejandrohdezma:sbt-github-mdoc:0.13.0:sbt-plugin"
    "com.alejandrohdezma:sbt-mdoc-toc:0.5.0:sbt-plugin"
    "com.alejandrohdezma:sbt-modules:0.4.1:sbt-plugin"
    "com.alejandrohdezma:sbt-scalafix-defaults:0.15.0:sbt-plugin"
    "com.alejandrohdezma:sbt-scalafmt-defaults:0.10.0:sbt-plugin"
    "com.github.sbt:sbt-ci-release:1.11.2:sbt-plugin"
    "com.github.sbt:sbt-header:5.11.0:sbt-plugin"
    "org.scalameta:sbt-mdoc:2.9.0:sbt-plugin"
    "org.scalameta:sbt-scalafmt:2.6.0:sbt-plugin"
    "org.typelevel:sbt-tpolecat:0.5.3:sbt-plugin"
  ]
}

common-settings {
  scala-versions = ["~2.12.21", "~2.13.18", "~3.3.7"]
}

documentation = [
  "org.http4s::http4s-blaze-client:0.23.17"
]

http4s-munit = [
  "io.circe::circe-parser:0.14.15"
  "org.http4s::http4s-client:0.23.34"
  "org.http4s::http4s-dsl:0.23.34"
  "org.scalameta::munit:1.3.0"
  "org.typelevel::munit-cats-effect:2.2.0"
  "ch.qos.logback:logback-classic:1.5.32:test"
  "com.dimafeng::testcontainers-scala-munit:0.44.1:test"
  "org.http4s::http4s-circe:0.23.34:test"
  "org.http4s::http4s-ember-client:0.23.34:test"
]
