# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name: Update documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  documentation:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          ref: master
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:1.8
          apps: sbt
      - name: Enable Coursier cache
        uses: coursier/cache-action@v5
      - name: Generate documentation
        run: sbt ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "Update documentation [skip ci]"
